### ISSUE TITLE
Size of the app too big on IOS

### ISSUE THREAD

**Issue by ask007learning** [timsneath/dadjokes#3]
Thank you for sharing the code. I have noticed that the app size on ios is 35.7 mb whereas on android it is only 7.8 mb.  I was under the impression that the app size would be similar on both platforms. Do you know why ios app size is 5 times more then andorid ?

**Comment by timsneath** [comment]
iOS is now small -- on modern iPhones, it's about 6MB; on older devices, it may be up to 16MB. 

![image](https://user-images.githubusercontent.com/2319867/81490924-a1e42d00-923c-11ea-808c-f0e3c6e65968.png)
