### ISSUE TITLE
Title bar looks too much like Android

### ISSUE THREAD

**Issue by MisterJimson** [timsneath/dadjokes#4]
Hey. Great sample and blog post for people getting started with Flutter.

It may make sense to have a less Android styled app/title bar. One of flutter's main draws is how you can implement your own design and have it consistent on multiple platforms. It would be great for a sample like this not to just directly use Android design, it may turn some people away who are expecting a canvas for their own design language.

A change as simple as centering the title bar would make it feel more like "app" and less of an "android app".

Either way great sample!

**Comment by timsneath** [comment]
Sorry that I never responded to this. I updated the design about a year ago and it now no longer looks like an Android app :)
